let
Source = Excel.CurrentWorkbook(){[Name="rawdata"]}[Content],
    #"Changed Type1" = Table.TransformColumnTypes(Source,{{"price/kg", type text}, {"price/lb", type text}, {"price/100g", type text}, {"price/non-weight_uom", type text}}),
    #"Replaced Value4" = Table.ReplaceValue(#"Changed Type1","",null,Replacer.ReplaceValue,{"price/kg","price/100g","price/non-weight_uom","price/lb"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","/ea","",Replacer.ReplaceText,{"price/kg","price/100g","price/non-weight_uom","price/lb"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Replaced Value5",{"zones"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Removed Columns2",{"measure", "title", "updated_by", "pagelayout", "pgx", "pgy", "flyerpage", "flyerpageid", "id"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Removed Columns1",{"modified"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Removed Columns3",{"offer_copy_fre"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns5","<MISSING IMAGE>",null,Replacer.ReplaceValue,{"image1","image2","image3","image4","image5","image6","image7"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","",null,Replacer.ReplaceValue,{"image1","image2","image3","image4","image5","image6","image7","price/lb","price/kg","price/100g","offer_copy","product_origin","price/non-weight_uom"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value1",{{"promo_start", type date}, {"promo_end", type date}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type","<MISSING IMAGE>","",Replacer.ReplaceText,{"image1", "image2", "image3", "image4", "image5", "image6", "image7"}),
    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value2",{{"image1", Text.Trim, type text}, {"image2", Text.Trim, type text}, {"image3", Text.Trim, type text}, {"image4", Text.Trim, type text}, {"image5", Text.Trim, type text}, {"image6", Text.Trim, type text}, {"image7", Text.Trim, type text}}),
    #"Replaced Value3" = Table.ReplaceValue(#"Trimmed Text","",null,Replacer.ReplaceValue,{"image1", "image2", "image3", "image4", "image5", "image6", "image7"}),
    image_org = Table.AddColumn(#"Replaced Value3", "image_org", each Text.Trim(Text.Replace(Text.Combine(List.Distinct(List.Sort(List.RemoveNulls({[image1],[image2]}))),"#(lf)"),"<MISSING IMAGE>",""))),
    price_a = Table.AddColumn(image_org, "price_a", each getPrice([#"price/non-weight_uom"],[#"price/100g"],[#"price/kg"],[#"price/lb"])),
    price_b = Table.AddColumn(price_a, "price_b", each let 
p = if [#"price/lb"] <> null then [#"price/kg"] else null,
l = if p <> null then Text.Combine(List.Sort(List.Distinct(List.Transform(Text.Split(p,","),Text.Trim))),",") else null
in l),
    #"Replaced Value6" = Table.ReplaceValue(price_b,",#(lf)",",",Replacer.ReplaceText,{"offer_type"}),
    offer_type = Table.AddColumn(#"Replaced Value6", "new_offertype", each getOfferType([offer_type], [#"price/non-weight_uom"], [#"price/100g"], [#"price/lb"], [#"price/kg"], [rewards_points], [offer_copy])),
    #"Removed Columns" = Table.RemoveColumns(offer_type,{"image1", "image2", "image3", "image4", "image5", "image6", "image7"}),
    #"Grouped Rows" = Table.Group(#"Removed Columns", {"project.Id", "page", "position", "product_origin", "offer_copy", "price_a", "price_b", "image_org", "rewards_points"}, {{"Data", each _, type table [Import Files=text, Name=text, project=text, Docket=number, Season=text, Banner=text, Week=text, project.Id=number, tab=text, promo_start=nullable date, promo_end=nullable date, page=text, folio=number, position=number, itemnumber=text, category=text, product_origin=nullable text, offer_copy=nullable text, offer_layout=any, offer_type=text, #"price/kg"=nullable text, #"price/lb"=nullable text, #"price/100g"=nullable text, #"price/non-weight_uom"=nullable text, rewards_points=text, assigned_logo=text, assigned_icon=text, instructions=text, image_org=text, price_a=text, price_b=nullable text, new_offertype=text]}}),
    banner = Table.AddColumn(#"Grouped Rows", "Banner", each [Data]{0}[Banner]),
    #"Added Custom1" = Table.AddColumn(banner, "Season", each [Data]{0}[Season]),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Week", each [Data]{0}[Week]),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "copy", each if [offer_copy] <> null and [offer_copy] <> "" then Text.Proper(Text.Combine(List.Distinct(List.RemoveNulls(List.Transform(Text.Split([offer_copy],"#(lf)"),Text.Trim))),"#(lf)")) else null),
    offer_type_org = Table.AddColumn(#"Added Custom3", "offer_type", each Text.Combine(List.Distinct(Table.Column([Data],"new_offertype")),",")),
    #"Removed Columns4" = Table.RemoveColumns(offer_type_org,{"offer_copy"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns4",{"project.Id", "Banner", "Season", "Week", "page", "position", "product_origin", "copy", "price_a", "price_b", "image_org","Data"}),
    origin = Table.AddColumn(#"Reordered Columns", "origin", each if [product_origin] <> null and [product_origin] <> "" then Text.Proper(Text.Combine(List.Distinct(List.RemoveNulls(List.Transform(Text.Split([product_origin],"#(lf)"),Text.Trim))),"#(lf)")) else null),
    #"Reordered Columns1" = Table.ReorderColumns(origin,{"project.Id", "Banner", "Season", "Week", "page", "position", "product_origin", "origin", "copy", "price_a", "price_b", "image_org", "Data"}),
    #"Removed Columns6" = Table.RemoveColumns(#"Reordered Columns1",{"product_origin"}),
    zones_org = Table.AddColumn(#"Removed Columns6", "zones_org", each Text.Combine(List.Distinct(Table.Column([Data],"tab")),",")),
    zones = Table.AddColumn(zones_org, "zones", each getZones([zones_org], [Banner], [page], [position])),
    item_number = Table.AddColumn(zones, "item_number", each Text.Combine(List.Distinct(List.Select(Text.Split(Text.Replace(Text.Combine(Table.Column([Data],"itemnumber"),"#(lf)"),",","#(lf)"),"#(lf)"),each _ <> "" and _ <> null)),",")),
    #"Reordered Columns2" = Table.ReorderColumns(item_number,{"project.Id", "Banner", "Season", "Week", "page", "position", "origin", "copy", "price_a", "price_b", "item_number", "image_org", "Data", "zones_org", "zones"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Reordered Columns2",{"project.Id", "Banner", "Season", "Week", "page", "position", "origin", "copy", "price_a", "price_b", "item_number", "image_org", "Data", "zones_org", "zones"}),
    rewards = Table.AddColumn(#"Reordered Columns3", "rewards_points_new", each try Text.Trim(Text.Split(Text.Combine(List.Distinct(List.Select(List.Transform(Table.Column([Data],"rewards_points"),each Text.Replace(_,"#(lf)","-")), each _ <> "" and _ <> null)),"#(lf)"),"-"){1}) otherwise null),
    #"Added Custom11" = Table.AddColumn(rewards, "instructions", each Text.Combine(List.Distinct(Table.Column([Data],"instructions")),"#(lf)")),
    Images = Table.AddColumn(#"Added Custom11", "images", each getImages(Text.Split([image_org],"#(lf)"))),
    #"Added Index" = Table.AddIndexColumn(Images, "Index", 0, 1, Int64.Type),
    #"Filtered Rows" = Table.SelectRows(#"Added Index", each ([page] <> null)),
    #"Added Custom15" = Table.AddColumn(#"Filtered Rows", "assigned_logo", each Text.Combine(List.Distinct(Table.Column([Data],"assigned_logo")),",")),
    #"Added Custom16" = Table.AddColumn(#"Added Custom15", "assigned_icon", each Text.Combine(List.Distinct(Table.Column([Data],"assigned_icon")),",")),
    #"Added Custom17" = Table.AddColumn(#"Added Custom16", "category", each Text.Combine(List.Distinct(Text.Split(Text.Combine(List.Distinct(Table.Column([Data],"category")),","),",")),",")),
    offer_copy = Table.AddColumn(#"Added Custom17", "new_offer_copy", each getOfferCopy([copy],[origin],[zones])),
    #"Reordered Columns4" = Table.ReorderColumns(offer_copy,{"project.Id", "Banner", "Season", "Week", "page", "position", "rewards_points", "origin", "copy", "new_offer_copy", "price_a", "price_b", "offer_type", "rewards_points_new", "item_number", "image_org", "Data", "zones_org", "zones", "instructions", "images", "Index", "assigned_logo", "assigned_icon", "category"}),
    #"Removed Columns7" = Table.RemoveColumns(#"Reordered Columns4",{"rewards_points"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns7", "offer_copy_orgin", each if [origin]=null or [origin] ="" then [new_offer_copy] else if List.Count(Text.Split([origin],";")) = 2 then 
getOfferCopyOrigin([new_offer_copy],Text.Split([origin],";"){0},Text.Split([origin],";"){1}) 
else getOfferCopyOrigin([new_offer_copy],[origin],null)),
    #"Reordered Columns5" = Table.ReorderColumns(#"Added Custom",{"project.Id", "Banner", "Season", "Week", "page", "position", "origin", "copy", "new_offer_copy", "offer_copy_orgin", "price_a", "price_b", "offer_type", "rewards_points_new", "item_number", "image_org", "Data", "zones_org", "zones", "instructions", "images", "Index", "assigned_logo", "assigned_icon", "category"}),
    #"Removed Columns8" = Table.RemoveColumns(#"Reordered Columns5",{"new_offer_copy"})
in
    #"Removed Columns8"