let
    #"Renamed Columns1" = Table.RenameColumns(rawdata,{{"Featured Item Number", "featured_item_number"}, {"Country of Origin", "country_of_origin"}, {"Grade", "grade"}, {"Item Name", "item_name"}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Renamed Columns1",{{"Category Name", "category_name"}, {"SBU", "sbu"}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Renamed Columns2",{{"Version", "version"}, {"Markets", "markets"}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Renamed Columns3",{{"Event Price", "event_price"}}),
    #"Renamed Columns5" = Table.RenameColumns(#"Renamed Columns4",{{"Regular Price", "regular_price"}}),
    #"Renamed Columns6" = Table.RenameColumns(#"Renamed Columns5",{{"Price per", "unit"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns6","unit","each",Replacer.ReplaceText,{"unit"}),
    #"Added Custom6" = Table.AddColumn(#"Replaced Value", "savings", each try if [regular_price]-[event_price] > 0 then [regular_price]-[event_price] else null otherwise null),
    #"Renamed Columns7" = Table.RenameColumns(#"Added Custom6",{{"Image Source", "image_source"}, {"Picked Up From Week", "picked_up_from_week"}, {"Multi Save (Deal Type)", "multi_save"}}),
    #"Renamed Columns8" = Table.RenameColumns(#"Renamed Columns7",{{"Offer Type", "offer_type"}}),
    #"Renamed Columns9" = Table.RenameColumns(#"Renamed Columns8",{{"Comments", "comments"}, {"Super Center Only", "super_center_only"}}),
    #"Renamed Columns10" = Table.RenameColumns(#"Renamed Columns9",{{"Page", "page"}, {"Adblock #", "adblock"}, {"Ad Block Theme", "ad_block_theme"}}),
    #"Renamed Columns11" = Table.RenameColumns(#"Renamed Columns10",{{"picked_up_from_week", "pickedup_from"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns11",{{"pickedup_from", type text}}),
    #"Grouped Rows" = Table.Group(#"Changed Type1", {"project", "page", "adblock", "markets", "event_price"}, {{"Data", each _, type table [Import Files=text, project=text, Docket=any, Season=text, Banner=any, Week=number, project.Id=number, tab=text, Preview=any, featured_item_number=text, country_of_origin=text, grade=text, item_name=text, URL=text, Online Only=text, Copy Description=text, ad_block_theme=text, sbu=text, Department Name=text, category_name=text, page=number, adblock=number, version=text, markets=text, event_price=any, regular_price=any, unit=nullable text, offer_type=text, comments=text, super_center_only=text, multi_save=text, image_source=text, pickedup_from=nullable text, savings=nullable number]}}),
    #"Added Custom8" = Table.AddColumn(#"Grouped Rows", "featured_item_numbers", each Text.Combine(Table.Column([Data],"featured_item_number"),",")),
    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "featured_items", each Text.Combine(Table.Column([Data],"item_name"),"#(cr)#(lf)")),
    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "Copy_Description", each [Data]{0}[Copy Description]),
    #"Added Custom14" = Table.AddColumn(#"Added Custom10", "combined_item_number", each Text.Combine(Table.Column([Data],"featured_item_number"),"/")),
    #"Added Custom15" = Table.AddColumn(#"Added Custom14", "sbu", each [Data]{0}[sbu]),
    #"Added Custom16" = Table.AddColumn(#"Added Custom15", "category_name", each [Data]{0}[category_name]),
    #"Added Custom17" = Table.AddColumn(#"Added Custom16", "version", each [Data]{0}[version]),
    #"Added Custom18" = Table.AddColumn(#"Added Custom17", "country_of_orgin", each Text.Combine(List.Distinct(Table.Column([Data],"country_of_origin")),",")),
    #"Added Custom19" = Table.AddColumn(#"Added Custom18", "grade", each Text.Combine(List.Distinct(Table.Column([Data],"grade")),",")),
    #"Added Custom20" = Table.AddColumn(#"Added Custom19", "image_source", each Text.Combine(List.Distinct(Table.Column([Data],"image_source")),",")),
    #"Added Custom21" = Table.AddColumn(#"Added Custom20", "pickedup_from", each Text.Combine(List.Distinct(Table.Column([Data],"pickedup_from")),",")),
    #"Added Custom22" = Table.AddColumn(#"Added Custom21", "comments", each Text.Combine(List.Distinct(Table.Column([Data],"comments")),",")),
    #"Added Custom23" = Table.AddColumn(#"Added Custom22", "offer_type", each [Data]{0}[offer_type]),
    #"Added Custom24" = Table.AddColumn(#"Added Custom23", "regular_price", each [Data]{0}[regular_price]),
    #"Added Custom26" = Table.AddColumn(#"Added Custom24", "savings", each [Data]{0}[savings]),
    #"Added Custom27" = Table.AddColumn(#"Added Custom26", "unit", each [Data]{0}[unit]),
    #"Added Custom28" = Table.AddColumn(#"Added Custom27", "multi_save", each [Data]{0}[multi_save]),
    #"Added Custom29" = Table.AddColumn(#"Added Custom28", "item_availability", each [Data]{0}[#"Item Availibility (Merchant)"]),
    #"Added Custom11" = Table.AddColumn(#"Added Custom29", "DataBase", each let x = [featured_item_numbers]
in Table.SelectRows(DataBase,each [Featured_item_numbers] = x )),
    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "offer_copy", each let x = try List.First(List.RemoveNulls(Table.Column([DataBase],"Offer_copy"))) otherwise [Copy_Description]
in if x = null then [Copy_Description] else x),
    #"Added Custom13" = Table.AddColumn(#"Added Custom12", "offer_copy_french", each try List.First(List.RemoveNulls(Table.Column([DataBase],"Offer_copy_french"))) otherwise null),
    #"Added Custom" = Table.AddColumn(#"Added Custom13", "assigned_images", each try List.First(Table.Column([DataBase],"assigned_images_lookup")) otherwise null),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "assigned_images_fre", each try Text.Combine(List.Transform(Table.Column(List.First(List.RemoveNulls(Table.Column([DataBase],"Assigned_images_fre"))),"Id"),Text.From),",") otherwise null),
    #"Renamed Columns13" = Table.RenameColumns(#"Added Custom1",{{"featured_item_numbers", "featured_item_number"}, {"featured_items", "item_name"}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns13"," ",",",Replacer.ReplaceText,{"markets"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value1",{"project", "offer_type", "version", "page", "adblock", "sbu", "markets", "category_name", "Copy_Description", "offer_copy", "item_name", "featured_item_number", "combined_item_number", "offer_copy_french", "event_price", "regular_price", "savings", "unit", "country_of_orgin", "grade", "multi_save", "image_source", "pickedup_from", "comments", "item_availability", "DataBase", "Data"})
in
    #"Reordered Columns"